<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<OutputType>WinExe</OutputType>
				<TargetFramework>net9.0-windows</TargetFramework>
				<Nullable>enable</Nullable>
				<ImplicitUsings>enable</ImplicitUsings>
				<UseWPF>true</UseWPF>
				<_ViewModelUtilsVersion>0.4.4-alpha002</_ViewModelUtilsVersion>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="Shipwreck.ViewModelUtils.PresentationFramework" Version="$(_ViewModelUtilsVersion)" />
		</ItemGroup>
		<ItemGroup>
		  <ProjectReference Include="..\Shipwreck.Aipri\Shipwreck.Aipri.csproj" />
		</ItemGroup>
</Project>
